version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: domains
    ports:
      - "5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d domains"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/domains
      - API_BASE_URL=https://httpbin.org  # for testing
    depends_on:
      db:
        condition: service_healthy
    command: tail -f /dev/null

volumes:
  postgres_data: